config/routes.rb
Rails.application.routes.draw do
  resources :jobbs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jobb.rb
class Jobb < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobbs_controller.rb
class JobbsController < ApplicationController
  before_action :set_jobb, only: %i[ show edit update destroy ]

  # GET /jobbs or /jobbs.json
  def index
    @jobbs = Jobb.all
  end

  # GET /jobbs/1 or /jobbs/1.json
  def show
    # binding.pry
  end

  # GET /jobbs/new
  def new
    @jobb = Jobb.new
  end

  # GET /jobbs/1/edit
  def edit
  end

  # POST /jobbs or /jobbs.json
  def create
    @jobb = Jobb.new(jobb_params)

    if @jobb.save
      redirect_to @jobb, notice: 'Job was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /jobbs/1 or /jobbs/1.json
  def update
    if @jobb.update(jobb_params)
      redirect_to @jobb, notice: 'Job was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /jobbs/1 or /jobbs/1.json
  def destroy
    @jobb.destroy

    redirect_to @jobb, notice: 'Job was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jobb
      @jobb = Jobb.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def jobb_params
      params.require(:jobb).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobbs_helper.rb
module JobbsHelper
end

app/views/jobbs/_form.html.erb
<%= form_with(model: jobb, data: { turbo_frame: 'new_jobb' }) do |form| %>
  <% if jobb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jobb.errors.count, "error") %> prohibited this jobb from being saved:</h2>

      <ul>
        <% jobb.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobbs/edit.html.erb
<h1>Editing Jobb</h1>

<%= turbo_frame_tag 'edit_jobb' do %>
  <%= render 'form', jobb: @jobb %>
<% end %>

<%= link_to 'Show', @jobb %> |
<%= link_to 'Back', jobbs_path %>

app/views/jobbs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobbs</h1>

<%= turbo_frame_tag 'jobbs' do %>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @jobbs.each do |jobb| %>
        <tr>
          <td><%= jobb.title %></td>
          <td><%= jobb.description %></td>
          <td><%= link_to 'Show', jobb %></td>
          <td><%= link_to 'Edit', edit_jobb_path(jobb) %></td>
          <td><%= button_to 'Destroy', jobb, method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<br>

<%= link_to 'New Jobb', new_jobb_path %>

app/views/jobbs/new.html.erb
<h1>New Jobb</h1>

<%= turbo_frame_tag 'new_jobb' do %>
  <%= render 'form', jobb: @jobb %>
<% end %>

<%= link_to 'Back', jobbs_path %>

app/views/jobbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @jobb.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @jobb.description %>
</p>

<%= link_to 'Edit', edit_jobb_path(@jobb) %> |
<%= link_to 'Back', jobbs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>